import fs from "node:fs";
import path from "node:path";
import {
  Workspace,
  ensureDir,
  sha256,
  loadSkillPackage,
  formatSkillResourceAppendix,
  assembleAllTaskShells,
  resolveBoundGuides,
  enrichTaskShellAppendix,
  taskShellContent,
  taskEntrySkillMarkdown,
  BOUND_GUIDES_MARKER,
  type DeliveryStage,
  type GuideDef,
  type TaskShell
} from "@harnessx/core";
import { computeTier, TARGETS, type AdapterCapabilities, type Tier } from "./capability.js";

/**
 * T-604: single-source → multi-target compilation.
 * Task shells are assembled from guide.workflow (+ optional guide.command override)
 * and bound skills/templates; projected as commands and/or task-entry skills.
 */

export const ADAPTER_VERSION = "1.0.0";

/** @deprecated use BOUND_GUIDES_MARKER from @harnessx/core */
export { BOUND_GUIDES_MARKER };

export interface CommandDef {
  name: string;
  description: string;
  run: string;
  stage: DeliveryStage;
  task: string;
  prompt?: string;
  /** Compile-time appendix from bound skills/templates (set by collectCommands). */
  appendix?: string;
}

export function commandFromShell(shell: TaskShell): CommandDef {
  return {
    name: shell.name,
    description: shell.description,
    run: shell.run,
    stage: shell.stage,
    task: shell.task,
    prompt: shell.body,
    appendix: shell.appendix
  };
}

/** Skills/templates bound to this stage/task. */
export function boundGuidesForCommand(ws: Workspace, stage: DeliveryStage, task: string): GuideDef[] {
  return resolveBoundGuides(ws, stage, task);
}

export function enrichCommandAppendix(ws: Workspace, c: CommandDef): string {
  return enrichTaskShellAppendix(ws, c.stage, c.task, resolveBoundGuides(ws, c.stage, c.task));
}

export function collectCommands(ws: Workspace): CommandDef[] {
  return assembleAllTaskShells(ws).map(commandFromShell);
}

/** Task-entry skill shells (same content as commands; for IDEs without commands). */
export function collectTaskEntrySkills(ws: Workspace): SkillSource[] {
  return assembleAllTaskShells(ws).map((shell) => {
    const content = taskEntrySkillMarkdown(shell);
    return {
      id: shell.name,
      root: `task-entry/${shell.name}`,
      content,
      files: [{ rel: "SKILL.md", content }],
      taskEntry: true as const
    };
  });
}

export function commandBody(c: CommandDef): string {
  const shellLike: TaskShell = {
    id: c.name,
    stage: c.stage,
    task: c.task,
    name: c.name,
    description: c.description,
    run: c.run,
    body: c.prompt ?? `# ${c.name}\n\n${c.description}`,
    appendix: c.appendix ?? "",
    boundGuides: []
  };
  return taskShellContent(shellLike);
}

export interface SkillFile {
  rel: string;
  content: string;
}

export interface SkillSource {
  id: string;
  root: string;
  content: string;
  files: SkillFile[];
  /** True when this skill is a compiled task-entry shell (not a domain guide.skill). */
  taskEntry?: boolean;
}

/** Inline SKILL.md plus resource appendix for flat rule/skill targets. */
export function skillInlineBody(skill: SkillSource): string {
  const appendix = formatSkillResourceAppendix(skill.id, { files: skill.files, entryRel: "SKILL.md" });
  return appendix ? `${skill.content.trimEnd()}\n\n${appendix}` : skill.content;
}

export function collectSkills(ws: Workspace): SkillSource[] {
  const harness = ws.readHarness();
  const out: SkillSource[] = [];
  for (const g of harness.guides) {
    if (g.kind !== "guide.skill") continue;
    try {
      const pkg = loadSkillPackage(ws.base, g.source);
      out.push({
        id: g.id,
        root: pkg.rootRel,
        content: pkg.entryContent,
        files: pkg.files
      });
      continue;
    } catch {
      /* legacy single-file source */
    }
    const f = path.join(ws.base, g.source);
    if (!fs.existsSync(f) || !fs.statSync(f).isFile()) continue;
    const content = fs.readFileSync(f, "utf8");
    const root = path.dirname(path.relative(ws.base, f)).replace(/\\/g, "/");
    out.push({ id: g.id, root, content, files: [{ rel: "SKILL.md", content }] });
  }
  return out;
}

export function rulesDigest(ws: Workspace): string {
  const parts: string[] = [];
  if (fs.existsSync(ws.constitutionFile)) {
    parts.push("## Constitution (highest priority)", fs.readFileSync(ws.constitutionFile, "utf8"));
  }
  parts.push(
    "## HarnessX ground rules",
    "- Work inside a change workspace; never edit harnessX/specs/ directly.",
    "- Never edit meta.yaml, harness.lock, fixtures.lock or approved fixtures by hand.",
    "- When a sensor fails, read fix_hint/agent_instruction before editing code.",
    "- Run `hx gate check <change> --stage <s> --task <t>` before claiming a task is complete."
  );
  return parts.join("\n\n");
}

export function withHeader(content: string, sourceNote: string, commentStyle: "html" | "hash" | "raw" = "html"): string {
  if (commentStyle === "raw") return content;
  const hash = sha256(content).slice(0, 16);
  const line = `GENERATED by harnessx adapter v${ADAPTER_VERSION} from ${sourceNote} — do not edit (hash:${hash})`;
  return commentStyle === "html" ? `<!-- ${line} -->\n${content}` : `# ${line}\n${content}`;
}

const HEADER_RE = /GENERATED by harnessx adapter v([\d.]+) from (.+?) — do not edit \(hash:([0-9a-f]{16})\)/;

export type DriftState = "ok" | "manually-edited" | "missing-header";

export function checkGeneratedFile(file: string): DriftState {
  const raw = fs.readFileSync(file, "utf8");
  const m = raw.match(HEADER_RE);
  if (!m) {
    if (file.endsWith(".json")) return "ok";
    return "missing-header";
  }
  const body = raw.split("\n").slice(1).join("\n");
  return sha256(body).slice(0, 16) === m[3] ? "ok" : "manually-edited";
}

export interface CompileResult {
  target: string;
  tier: Tier;
  files: string[];
  skipped: string[];
}

export type TargetEmitter = (ws: Workspace, ctx: EmitContext) => { files: string[]; skipped: string[] };

export interface EmitContext {
  commands: CommandDef[];
  /** Domain guide.skill packages. */
  skills: SkillSource[];
  /** Task-entry shells as skills (for IDEs without native commands). */
  taskEntrySkills: SkillSource[];
  capabilities: AdapterCapabilities;
  rules: string;
  write: (rel: string, content: string, style?: "html" | "hash" | "raw", sourceNote?: string) => string;
}

export function makeEmitContext(ws: Workspace, capabilities: AdapterCapabilities): Omit<EmitContext, "write"> {
  return {
    commands: collectCommands(ws),
    skills: collectSkills(ws),
    taskEntrySkills: collectTaskEntrySkills(ws),
    capabilities,
    rules: rulesDigest(ws)
  };
}

/** Emit slash-command files when the target supports commands. */
export function emitCommandFiles(ctx: EmitContext, dirPrefix: string): void {
  if (!ctx.capabilities.commands) return;
  for (const c of ctx.commands) {
    ctx.write(`${dirPrefix}/${c.name}.md`, commandBody(c));
  }
}

/** Emit task-entry skills when the target lacks commands but has a skills directory. */
export function emitTaskEntrySkillDirs(ctx: EmitContext, skillsRoot: string): void {
  if (ctx.capabilities.commands) return;
  if (!ctx.capabilities.skills) return;
  for (const s of ctx.taskEntrySkills) {
    for (const f of s.files) {
      const rel = f.rel.replace(/\\/g, "/");
      ctx.write(`${skillsRoot}/${s.id}/${rel}`, f.content, "html", s.root);
    }
  }
}

/** Markdown section for task entrypoints (inline / AGENTS.md). */
export function taskEntryInlineSection(ctx: EmitContext): string {
  if (ctx.capabilities.commands || !ctx.taskEntrySkills.length) return "";
  return [
    "",
    "## Task entrypoints",
    "",
    "These are task shells (same content as slash commands on command-capable IDEs).",
    "Invoke by asking the agent to run the named delivery task.",
    "",
    ctx.taskEntrySkills.map((s) => skillInlineBody(s)).join("\n\n---\n\n"),
    ""
  ].join("\n");
}

export function compileTarget(ws: Workspace, target: string, emitter: TargetEmitter): CompileResult {
  const spec = TARGETS[target];
  if (!spec) throw new Error(`unknown adapter target: ${target}`);
  const files: string[] = [];
  const ctx: EmitContext = {
    ...makeEmitContext(ws, spec.capabilities),
    write: (rel, content, style = "html", sourceNote = "harnessX/assets") => {
      const abs = path.join(ws.root, rel);
      ensureDir(path.dirname(abs));
      fs.writeFileSync(abs, withHeader(content, sourceNote, style));
      files.push(rel);
      return rel;
    }
  };
  const res = emitter(ws, ctx);
  return { target, tier: computeTier(spec.capabilities), files: [...files, ...res.files], skipped: res.skipped };
}
